<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CountriesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('countries')->truncate();

        $countries = [
            ["name" => "Afghanistan", "iso2" => "AF", "iso3" => "AFG", "phone_code" => "93", "currency_code" => "AFN"],
            ["name" => "Aland Islands", "iso2" => "AX", "iso3" => "ALA", "phone_code" => "358", "currency_code" => "EUR"],
            ["name" => "Albania", "iso2" => "AL", "iso3" => "ALB", "phone_code" => "355", "currency_code" => "ALL"],
            ["name" => "Algeria", "iso2" => "DZ", "iso3" => "DZA", "phone_code" => "213", "currency_code" => "DZD"],
            ["name" => "American Samoa", "iso2" => "AS", "iso3" => "ASM", "phone_code" => "1684", "currency_code" => "USD"],
            ["name" => "Andorra", "iso2" => "AD", "iso3" => "AND", "phone_code" => "376", "currency_code" => "EUR"],
            ["name" => "Angola", "iso2" => "AO", "iso3" => "AGO", "phone_code" => "244", "currency_code" => "AOA"],
            ["name" => "Anguilla", "iso2" => "AI", "iso3" => "AIA", "phone_code" => "1264", "currency_code" => "XCD"],
            ["name" => "Antarctica", "iso2" => "AQ", "iso3" => "ATA", "phone_code" => "672", "currency_code" => "AQD"],
            ["name" => "Antigua and Barbuda", "iso2" => "AG", "iso3" => "ATG", "phone_code" => "1268", "currency_code" => "XCD"],
            ["name" => "Argentina", "iso2" => "AR", "iso3" => "ARG", "phone_code" => "54", "currency_code" => "ARS"],
            ["name" => "Armenia", "iso2" => "AM", "iso3" => "ARM", "phone_code" => "374", "currency_code" => "AMD"],
            ["name" => "Aruba", "iso2" => "AW", "iso3" => "ABW", "phone_code" => "297", "currency_code" => "AWG"],
            ["name" => "Australia", "iso2" => "AU", "iso3" => "AUS", "phone_code" => "61", "currency_code" => "AUD"],
            ["name" => "Austria", "iso2" => "AT", "iso3" => "AUT", "phone_code" => "43", "currency_code" => "EUR"],
            ["name" => "Azerbaijan", "iso2" => "AZ", "iso3" => "AZE", "phone_code" => "994", "currency_code" => "AZN"],
            ["name" => "Bahamas", "iso2" => "BS", "iso3" => "BHS", "phone_code" => "1242", "currency_code" => "BSD"],
            ["name" => "Bahrain", "iso2" => "BH", "iso3" => "BHR", "phone_code" => "973", "currency_code" => "BHD"],
            ["name" => "Bangladesh", "iso2" => "BD", "iso3" => "BGD", "phone_code" => "880", "currency_code" => "BDT"],
            ["name" => "Barbados", "iso2" => "BB", "iso3" => "BRB", "phone_code" => "1246", "currency_code" => "BBD"],
            ["name" => "Belarus", "iso2" => "BY", "iso3" => "BLR", "phone_code" => "375", "currency_code" => "BYN"],
            ["name" => "Belgium", "iso2" => "BE", "iso3" => "BEL", "phone_code" => "32", "currency_code" => "EUR"],
            ["name" => "Belize", "iso2" => "BZ", "iso3" => "BLZ", "phone_code" => "501", "currency_code" => "BZD"],
            ["name" => "Benin", "iso2" => "BJ", "iso3" => "BEN", "phone_code" => "229", "currency_code" => "XOF"],
            ["name" => "Bermuda", "iso2" => "BM", "iso3" => "BMU", "phone_code" => "1441", "currency_code" => "BMD"],
            ["name" => "Bhutan", "iso2" => "BT", "iso3" => "BTN", "phone_code" => "975", "currency_code" => "BTN"],
            ["name" => "Bolivia", "iso2" => "BO", "iso3" => "BOL", "phone_code" => "591", "currency_code" => "BOB"],
            ["name" => "Bosnia and Herzegovina", "iso2" => "BA", "iso3" => "BIH", "phone_code" => "387", "currency_code" => "BAM"],
            ["name" => "Botswana", "iso2" => "BW", "iso3" => "BWA", "phone_code" => "267", "currency_code" => "BWP"],
            ["name" => "Brazil", "iso2" => "BR", "iso3" => "BRA", "phone_code" => "55", "currency_code" => "BRL"],
            ["name" => "British Indian Ocean Territory", "iso2" => "IO", "iso3" => "IOT", "phone_code" => "246", "currency_code" => "USD"],
            ["name" => "Brunei Darussalam", "iso2" => "BN", "iso3" => "BRN", "phone_code" => "673", "currency_code" => "BND"],
            ["name" => "Bulgaria", "iso2" => "BG", "iso3" => "BGR", "phone_code" => "359", "currency_code" => "BGN"],
            ["name" => "Burkina Faso", "iso2" => "BF", "iso3" => "BFA", "phone_code" => "226", "currency_code" => "XOF"],
            ["name" => "Burundi", "iso2" => "BI", "iso3" => "BDI", "phone_code" => "257", "currency_code" => "BIF"],
            ["name" => "Cambodia", "iso2" => "KH", "iso3" => "KHM", "phone_code" => "855", "currency_code" => "KHR"],
            ["name" => "Cameroon", "iso2" => "CM", "iso3" => "CMR", "phone_code" => "237", "currency_code" => "XAF"],
            ["name" => "Canada", "iso2" => "CA", "iso3" => "CAN", "phone_code" => "1", "currency_code" => "CAD"],
            ["name" => "Cape Verde", "iso2" => "CV", "iso3" => "CPV", "phone_code" => "238", "currency_code" => "CVE"],
            ["name" => "Cayman Islands", "iso2" => "KY", "iso3" => "CYM", "phone_code" => "1345", "currency_code" => "KYD"],
            ["name" => "Central African Republic", "iso2" => "CF", "iso3" => "CAF", "phone_code" => "236", "currency_code" => "XAF"],
            ["name" => "Chad", "iso2" => "TD", "iso3" => "TCD", "phone_code" => "235", "currency_code" => "XAF"],
            ["name" => "Chile", "iso2" => "CL", "iso3" => "CHL", "phone_code" => "56", "currency_code" => "CLP"],
            ["name" => "China", "iso2" => "CN", "iso3" => "CHN", "phone_code" => "86", "currency_code" => "CNY"],
            ["name" => "Colombia", "iso2" => "CO", "iso3" => "COL", "phone_code" => "57", "currency_code" => "COP"],
            ["name" => "Comoros", "iso2" => "KM", "iso3" => "COM", "phone_code" => "269", "currency_code" => "KMF"],
            ["name" => "Congo (Brazzaville)", "iso2" => "CG", "iso3" => "COG", "phone_code" => "242", "currency_code" => "XAF"],
            ["name" => "Congo (Kinshasa)", "iso2" => "CD", "iso3" => "COD", "phone_code" => "243", "currency_code" => "CDF"],
            ["name" => "Costa Rica", "iso2" => "CR", "iso3" => "CRI", "phone_code" => "506", "currency_code" => "CRC"],
            ["name" => "Croatia", "iso2" => "HR", "iso3" => "HRV", "phone_code" => "385", "currency_code" => "EUR"],
            ["name" => "Cuba", "iso2" => "CU", "iso3" => "CUB", "phone_code" => "53", "currency_code" => "CUP"],
            ["name" => "Cyprus", "iso2" => "CY", "iso3" => "CYP", "phone_code" => "357", "currency_code" => "EUR"],
            ["name" => "Czech Republic", "iso2" => "CZ", "iso3" => "CZE", "phone_code" => "420", "currency_code" => "CZK"],
            ["name" => "Denmark", "iso2" => "DK", "iso3" => "DNK", "phone_code" => "45", "currency_code" => "DKK"],
            ["name" => "Djibouti", "iso2" => "DJ", "iso3" => "DJI", "phone_code" => "253", "currency_code" => "DJF"],
            ["name" => "Dominica", "iso2" => "DM", "iso3" => "DMA", "phone_code" => "1767", "currency_code" => "XCD"],
            ["name" => "Dominican Republic", "iso2" => "DO", "iso3" => "DOM", "phone_code" => "1809", "currency_code" => "DOP"],
            ["name" => "Ecuador", "iso2" => "EC", "iso3" => "ECU", "phone_code" => "593", "currency_code" => "USD"],
            ["name" => "Egypt", "iso2" => "EG", "iso3" => "EGY", "phone_code" => "20", "currency_code" => "EGP"],
            ["name" => "El Salvador", "iso2" => "SV", "iso3" => "SLV", "phone_code" => "503", "currency_code" => "USD"],
            ["name" => "Equatorial Guinea", "iso2" => "GQ", "iso3" => "GNQ", "phone_code" => "240", "currency_code" => "XAF"],
            ["name" => "Eritrea", "iso2" => "ER", "iso3" => "ERI", "phone_code" => "291", "currency_code" => "ERN"],
            ["name" => "Estonia", "iso2" => "EE", "iso3" => "EST", "phone_code" => "372", "currency_code" => "EUR"],
            ["name" => "Eswatini", "iso2" => "SZ", "iso3" => "SWZ", "phone_code" => "268", "currency_code" => "SZL"],
            ["name" => "Ethiopia", "iso2" => "ET", "iso3" => "ETH", "phone_code" => "251", "currency_code" => "ETB"],
            ["name" => "Fiji", "iso2" => "FJ", "iso3" => "FJI", "phone_code" => "679", "currency_code" => "FJD"],
            ["name" => "Finland", "iso2" => "FI", "iso3" => "FIN", "phone_code" => "358", "currency_code" => "EUR"],
            ["name" => "France", "iso2" => "FR", "iso3" => "FRA", "phone_code" => "33", "currency_code" => "EUR"],
            ["name" => "Gabon", "iso2" => "GA", "iso3" => "GAB", "phone_code" => "241", "currency_code" => "XAF"],
            ["name" => "Gambia", "iso2" => "GM", "iso3" => "GMB", "phone_code" => "220", "currency_code" => "GMD"],
            ["name" => "Georgia", "iso2" => "GE", "iso3" => "GEO", "phone_code" => "995", "currency_code" => "GEL"],
            ["name" => "Germany", "iso2" => "DE", "iso3" => "DEU", "phone_code" => "49", "currency_code" => "EUR"],
            ["name" => "Ghana", "iso2" => "GH", "iso3" => "GHA", "phone_code" => "233", "currency_code" => "GHS"],
            ["name" => "Gibraltar", "iso2" => "GI", "iso3" => "GIB", "phone_code" => "350", "currency_code" => "GIP"],
            ["name" => "Greece", "iso2" => "GR", "iso3" => "GRC", "phone_code" => "30", "currency_code" => "EUR"],
            ["name" => "Greenland", "iso2" => "GL", "iso3" => "GRL", "phone_code" => "299", "currency_code" => "DKK"],
            ["name" => "Grenada", "iso2" => "GD", "iso3" => "GRD", "phone_code" => "1473", "currency_code" => "XCD"],
            ["name" => "Guam", "iso2" => "GU", "iso3" => "GUM", "phone_code" => "1671", "currency_code" => "USD"],
            ["name" => "Guatemala", "iso2" => "GT", "iso3" => "GTM", "phone_code" => "502", "currency_code" => "GTQ"],
            ["name" => "Guernsey", "iso2" => "GG", "iso3" => "GGY", "phone_code" => "44", "currency_code" => "GBP"],
            ["name" => "Guinea", "iso2" => "GN", "iso3" => "GIN", "phone_code" => "224", "currency_code" => "GNF"],
            ["name" => "Guinea-Bissau", "iso2" => "GW", "iso3" => "GNB", "phone_code" => "245", "currency_code" => "XOF"],
            ["name" => "Guyana", "iso2" => "GY", "iso3" => "GUY", "phone_code" => "592", "currency_code" => "GYD"],
            ["name" => "Haiti", "iso2" => "HT", "iso3" => "HTI", "phone_code" => "509", "currency_code" => "HTG"],
            ["name" => "Honduras", "iso2" => "HN", "iso3" => "HND", "phone_code" => "504", "currency_code" => "HNL"],
            ["name" => "Hong Kong", "iso2" => "HK", "iso3" => "HKG", "phone_code" => "852", "currency_code" => "HKD"],
            ["name" => "Hungary", "iso2" => "HU", "iso3" => "HUN", "phone_code" => "36", "currency_code" => "HUF"],
            ["name" => "Iceland", "iso2" => "IS", "iso3" => "ISL", "phone_code" => "354", "currency_code" => "ISK"],
            ["name" => "India", "iso2" => "IN", "iso3" => "IND", "phone_code" => "91", "currency_code" => "INR"],
            ["name" => "Indonesia", "iso2" => "ID", "iso3" => "IDN", "phone_code" => "62", "currency_code" => "IDR"],
            ["name" => "Iran", "iso2" => "IR", "iso3" => "IRN", "phone_code" => "98", "currency_code" => "IRR"],
            ["name" => "Iraq", "iso2" => "IQ", "iso3" => "IRQ", "phone_code" => "964", "currency_code" => "IQD"],
            ["name" => "Ireland", "iso2" => "IE", "iso3" => "IRL", "phone_code" => "353", "currency_code" => "EUR"],
            ["name" => "Isle of Man", "iso2" => "IM", "iso3" => "IMN", "phone_code" => "44", "currency_code" => "GBP"],
            ["name" => "Israel", "iso2" => "IL", "iso3" => "ISR", "phone_code" => "972", "currency_code" => "ILS"],
            ["name" => "Italy", "iso2" => "IT", "iso3" => "ITA", "phone_code" => "39", "currency_code" => "EUR"],
            ["name" => "Jamaica", "iso2" => "JM", "iso3" => "JAM", "phone_code" => "1876", "currency_code" => "JMD"],
            ["name" => "Japan", "iso2" => "JP", "iso3" => "JPN", "phone_code" => "81", "currency_code" => "JPY"],
            ["name" => "Jersey", "iso2" => "JE", "iso3" => "JEY", "phone_code" => "44", "currency_code" => "GBP"],
            ["name" => "Jordan", "iso2" => "JO", "iso3" => "JOR", "phone_code" => "962", "currency_code" => "JOD"],
            ["name" => "Kazakhstan", "iso2" => "KZ", "iso3" => "KAZ", "phone_code" => "7", "currency_code" => "KZT"],
            ["name" => "Kenya", "iso2" => "KE", "iso3" => "KEN", "phone_code" => "254", "currency_code" => "KES"],
            ["name" => "Kiribati", "iso2" => "KI", "iso3" => "KIR", "phone_code" => "686", "currency_code" => "KID"],
            ["name" => "Korea North", "iso2" => "KP", "iso3" => "PRK", "phone_code" => "850", "currency_code" => "KPW"],
            ["name" => "Korea South", "iso2" => "KR", "iso3" => "KOR", "phone_code" => "82", "currency_code" => "KRW"],
            ["name" => "Kuwait", "iso2" => "KW", "iso3" => "KWT", "phone_code" => "965", "currency_code" => "KWD"],
            ["name" => "Kyrgyzstan", "iso2" => "KG", "iso3" => "KGZ", "phone_code" => "996", "currency_code" => "KGS"],
            ["name" => "Laos", "iso2" => "LA", "iso3" => "LAO", "phone_code" => "856", "currency_code" => "LAK"],
            ["name" => "Latvia", "iso2" => "LV", "iso3" => "LVA", "phone_code" => "371", "currency_code" => "EUR"],
            ["name" => "Lebanon", "iso2" => "LB", "iso3" => "LBN", "phone_code" => "961", "currency_code" => "LBP"],
            ["name" => "Lesotho", "iso2" => "LS", "iso3" => "LSO", "phone_code" => "266", "currency_code" => "LSL"],
            ["name" => "Liberia", "iso2" => "LR", "iso3" => "LBR", "phone_code" => "231", "currency_code" => "LRD"],
            ["name" => "Libya", "iso2" => "LY", "iso3" => "LBY", "phone_code" => "218", "currency_code" => "LYD"],
            ["name" => "Liechtenstein", "iso2" => "LI", "iso3" => "LIE", "phone_code" => "423", "currency_code" => "CHF"],
            ["name" => "Lithuania", "iso2" => "LT", "iso3" => "LTU", "phone_code" => "370", "currency_code" => "EUR"],
            ["name" => "Luxembourg", "iso2" => "LU", "iso3" => "LUX", "phone_code" => "352", "currency_code" => "EUR"],
            ["name" => "Macao", "iso2" => "MO", "iso3" => "MAC", "phone_code" => "853", "currency_code" => "MOP"],
            ["name" => "Madagascar", "iso2" => "MG", "iso3" => "MDG", "phone_code" => "261", "currency_code" => "MGA"],
            ["name" => "Malawi", "iso2" => "MW", "iso3" => "MWI", "phone_code" => "265", "currency_code" => "MWK"],
            ["name" => "Malaysia", "iso2" => "MY", "iso3" => "MYS", "phone_code" => "60", "currency_code" => "MYR"],
            ["name" => "Maldives", "iso2" => "MV", "iso3" => "MDV", "phone_code" => "960", "currency_code" => "MVR"],
            ["name" => "Mali", "iso2" => "ML", "iso3" => "MLI", "phone_code" => "223", "currency_code" => "XOF"],
            ["name" => "Malta", "iso2" => "MT", "iso3" => "MLT", "phone_code" => "356", "currency_code" => "EUR"],
            ["name" => "Marshall Islands", "iso2" => "MH", "iso3" => "MHL", "phone_code" => "692", "currency_code" => "USD"],
            ["name" => "Mauritania", "iso2" => "MR", "iso3" => "MRT", "phone_code" => "222", "currency_code" => "MRU"],
            ["name" => "Mauritius", "iso2" => "MU", "iso3" => "MUS", "phone_code" => "230", "currency_code" => "MUR"],
            ["name" => "Mexico", "iso2" => "MX", "iso3" => "MEX", "phone_code" => "52", "currency_code" => "MXN"],
            ["name" => "Micronesia", "iso2" => "FM", "iso3" => "FSM", "phone_code" => "691", "currency_code" => "USD"],
            ["name" => "Moldova", "iso2" => "MD", "iso3" => "MDA", "phone_code" => "373", "currency_code" => "MDL"],
            ["name" => "Monaco", "iso2" => "MC", "iso3" => "MCO", "phone_code" => "377", "currency_code" => "EUR"],
            ["name" => "Mongolia", "iso2" => "MN", "iso3" => "MNG", "phone_code" => "976", "currency_code" => "MNT"],
            ["name" => "Montenegro", "iso2" => "ME", "iso3" => "MNE", "phone_code" => "382", "currency_code" => "EUR"],
            ["name" => "Montserrat", "iso2" => "MS", "iso3" => "MSR", "phone_code" => "1664", "currency_code" => "XCD"],
            ["name" => "Morocco", "iso2" => "MA", "iso3" => "MAR", "phone_code" => "212", "currency_code" => "MAD"],
            ["name" => "Mozambique", "iso2" => "MZ", "iso3" => "MOZ", "phone_code" => "258", "currency_code" => "MZN"],
            ["name" => "Myanmar", "iso2" => "MM", "iso3" => "MMR", "phone_code" => "95", "currency_code" => "MMK"],
            ["name" => "Namibia", "iso2" => "NA", "iso3" => "NAM", "phone_code" => "264", "currency_code" => "NAD"],
            ["name" => "Nauru", "iso2" => "NR", "iso3" => "NRU", "phone_code" => "674", "currency_code" => "AUD"],
            ["name" => "Nepal", "iso2" => "NP", "iso3" => "NPL", "phone_code" => "977", "currency_code" => "NPR"],
            ["name" => "Netherlands", "iso2" => "NL", "iso3" => "NLD", "phone_code" => "31", "currency_code" => "EUR"],
            ["name" => "New Zealand", "iso2" => "NZ", "iso3" => "NZL", "phone_code" => "64", "currency_code" => "NZD"],
            ["name" => "Nicaragua", "iso2" => "NI", "iso3" => "NIC", "phone_code" => "505", "currency_code" => "NIO"],
            ["name" => "Niger", "iso2" => "NE", "iso3" => "NER", "phone_code" => "227", "currency_code" => "XOF"],
            ["name" => "Nigeria", "iso2" => "NG", "iso3" => "NGA", "phone_code" => "234", "currency_code" => "NGN"],
            ["name" => "North Macedonia", "iso2" => "MK", "iso3" => "MKD", "phone_code" => "389", "currency_code" => "MKD"],
            ["name" => "Norway", "iso2" => "NO", "iso3" => "NOR", "phone_code" => "47", "currency_code" => "NOK"],
            ["name" => "Oman", "iso2" => "OM", "iso3" => "OMN", "phone_code" => "968", "currency_code" => "OMR"],
            ["name" => "Pakistan", "iso2" => "PK", "iso3" => "PAK", "phone_code" => "92", "currency_code" => "PKR"],
            ["name" => "Palau", "iso2" => "PW", "iso3" => "PLW", "phone_code" => "680", "currency_code" => "USD"],
            ["name" => "Palestine", "iso2" => "PS", "iso3" => "PSE", "phone_code" => "970", "currency_code" => "ILS"],
            ["name" => "Panama", "iso2" => "PA", "iso3" => "PAN", "phone_code" => "507", "currency_code" => "PAB"],
            ["name" => "Papua New Guinea", "iso2" => "PG", "iso3" => "PNG", "phone_code" => "675", "currency_code" => "PGK"],
            ["name" => "Paraguay", "iso2" => "PY", "iso3" => "PRY", "phone_code" => "595", "currency_code" => "PYG"],
            ["name" => "Peru", "iso2" => "PE", "iso3" => "PER", "phone_code" => "51", "currency_code" => "PEN"],
            ["name" => "Philippines", "iso2" => "PH", "iso3" => "PHL", "phone_code" => "63", "currency_code" => "PHP"],
            ["name" => "Poland", "iso2" => "PL", "iso3" => "POL", "phone_code" => "48", "currency_code" => "PLN"],
            ["name" => "Portugal", "iso2" => "PT", "iso3" => "PRT", "phone_code" => "351", "currency_code" => "EUR"],
            ["name" => "Qatar", "iso2" => "QA", "iso3" => "QAT", "phone_code" => "974", "currency_code" => "QAR"],
            ["name" => "Romania", "iso2" => "RO", "iso3" => "ROU", "phone_code" => "40", "currency_code" => "RON"],
            ["name" => "Russia", "iso2" => "RU", "iso3" => "RUS", "phone_code" => "7", "currency_code" => "RUB"],
            ["name" => "Rwanda", "iso2" => "RW", "iso3" => "RWA", "phone_code" => "250", "currency_code" => "RWF"],
            ["name" => "Saint Kitts and Nevis", "iso2" => "KN", "iso3" => "KNA", "phone_code" => "1869", "currency_code" => "XCD"],
            ["name" => "Saint Lucia", "iso2" => "LC", "iso3" => "LCA", "phone_code" => "1758", "currency_code" => "XCD"],
            ["name" => "Saint Vincent and the Grenadines", "iso2" => "VC", "iso3" => "VCT", "phone_code" => "1784", "currency_code" => "XCD"],
            ["name" => "Samoa", "iso2" => "WS", "iso3" => "WSM", "phone_code" => "685", "currency_code" => "WST"],
            ["name" => "San Marino", "iso2" => "SM", "iso3" => "SMR", "phone_code" => "378", "currency_code" => "EUR"],
            ["name" => "Sao Tome and Principe", "iso2" => "ST", "iso3" => "STP", "phone_code" => "239", "currency_code" => "STN"],
            ["name" => "Saudi Arabia", "iso2" => "SA", "iso3" => "SAU", "phone_code" => "966", "currency_code" => "SAR"],
            ["name" => "Senegal", "iso2" => "SN", "iso3" => "SEN", "phone_code" => "221", "currency_code" => "XOF"],
            ["name" => "Serbia", "iso2" => "RS", "iso3" => "SRB", "phone_code" => "381", "currency_code" => "RSD"],
            ["name" => "Seychelles", "iso2" => "SC", "iso3" => "SYC", "phone_code" => "248", "currency_code" => "SCR"],
            ["name" => "Sierra Leone", "iso2" => "SL", "iso3" => "SLE", "phone_code" => "232", "currency_code" => "SLL"],
            ["name" => "Singapore", "iso2" => "SG", "iso3" => "SGP", "phone_code" => "65", "currency_code" => "SGD"],
            ["name" => "Slovakia", "iso2" => "SK", "iso3" => "SVK", "phone_code" => "421", "currency_code" => "EUR"],
            ["name" => "Slovenia", "iso2" => "SI", "iso3" => "SVN", "phone_code" => "386", "currency_code" => "EUR"],
            ["name" => "Solomon Islands", "iso2" => "SB", "iso3" => "SLB", "phone_code" => "677", "currency_code" => "SBD"],
            ["name" => "Somalia", "iso2" => "SO", "iso3" => "SOM", "phone_code" => "252", "currency_code" => "SOS"],
            ["name" => "South Africa", "iso2" => "ZA", "iso3" => "ZAF", "phone_code" => "27", "currency_code" => "ZAR"],
            ["name" => "South Sudan", "iso2" => "SS", "iso3" => "SSD", "phone_code" => "211", "currency_code" => "SSP"],
            ["name" => "Spain", "iso2" => "ES", "iso3" => "ESP", "phone_code" => "34", "currency_code" => "EUR"],
            ["name" => "Sri Lanka", "iso2" => "LK", "iso3" => "LKA", "phone_code" => "94", "currency_code" => "LKR"],
            ["name" => "Sudan", "iso2" => "SD", "iso3" => "SDN", "phone_code" => "249", "currency_code" => "SDG"],
            ["name" => "Suriname", "iso2" => "SR", "iso3" => "SUR", "phone_code" => "597", "currency_code" => "SRD"],
            ["name" => "Sweden", "iso2" => "SE", "iso3" => "SWE", "phone_code" => "46", "currency_code" => "SEK"],
            ["name" => "Switzerland", "iso2" => "CH", "iso3" => "CHE", "phone_code" => "41", "currency_code" => "CHF"],
            ["name" => "Syria", "iso2" => "SY", "iso3" => "SYR", "phone_code" => "963", "currency_code" => "SYP"],
            ["name" => "Taiwan", "iso2" => "TW", "iso3" => "TWN", "phone_code" => "886", "currency_code" => "TWD"],
            ["name" => "Tajikistan", "iso2" => "TJ", "iso3" => "TJK", "phone_code" => "992", "currency_code" => "TJS"],
            ["name" => "Tanzania", "iso2" => "TZ", "iso3" => "TZA", "phone_code" => "255", "currency_code" => "TZS"],
            ["name" => "Thailand", "iso2" => "TH", "iso3" => "THA", "phone_code" => "66", "currency_code" => "THB"],
            ["name" => "Timor-Leste", "iso2" => "TL", "iso3" => "TLS", "phone_code" => "670", "currency_code" => "USD"],
            ["name" => "Togo", "iso2" => "TG", "iso3" => "TGO", "phone_code" => "228", "currency_code" => "XOF"],
            ["name" => "Tonga", "iso2" => "TO", "iso3" => "TON", "phone_code" => "676", "currency_code" => "TOP"],
            ["name" => "Trinidad and Tobago", "iso2" => "TT", "iso3" => "TTO", "phone_code" => "1868", "currency_code" => "TTD"],
            ["name" => "Tunisia", "iso2" => "TN", "iso3" => "TUN", "phone_code" => "216", "currency_code" => "TND"],
            ["name" => "Turkey", "iso2" => "TR", "iso3" => "TUR", "phone_code" => "90", "currency_code" => "TRY"],
            ["name" => "Turkmenistan", "iso2" => "TM", "iso3" => "TKM", "phone_code" => "993", "currency_code" => "TMT"],
            ["name" => "Tuvalu", "iso2" => "TV", "iso3" => "TUV", "phone_code" => "688", "currency_code" => "AUD"],
            ["name" => "Uganda", "iso2" => "UG", "iso3" => "UGA", "phone_code" => "256", "currency_code" => "UGX"],
            ["name" => "Ukraine", "iso2" => "UA", "iso3" => "UKR", "phone_code" => "380", "currency_code" => "UAH"],
            ["name" => "United Arab Emirates", "iso2" => "AE", "iso3" => "ARE", "phone_code" => "971", "currency_code" => "AED"],
            ["name" => "United Kingdom", "iso2" => "GB", "iso3" => "GBR", "phone_code" => "44", "currency_code" => "GBP"],
            ["name" => "United States", "iso2" => "US", "iso3" => "USA", "phone_code" => "1", "currency_code" => "USD"],
            ["name" => "Uruguay", "iso2" => "UY", "iso3" => "URY", "phone_code" => "598", "currency_code" => "UYU"],
            ["name" => "Uzbekistan", "iso2" => "UZ", "iso3" => "UZB", "phone_code" => "998", "currency_code" => "UZS"],
            ["name" => "Vanuatu", "iso2" => "VU", "iso3" => "VUT", "phone_code" => "678", "currency_code" => "VUV"],
            ["name" => "Vatican", "iso2" => "VA", "iso3" => "VAT", "phone_code" => "379", "currency_code" => "EUR"],
            ["name" => "Venezuela", "iso2" => "VE", "iso3" => "VEN", "phone_code" => "58", "currency_code" => "VES"],
            ["name" => "Vietnam", "iso2" => "VN", "iso3" => "VNM", "phone_code" => "84", "currency_code" => "VND"],
            ["name" => "Yemen", "iso2" => "YE", "iso3" => "YEM", "phone_code" => "967", "currency_code" => "YER"],
            ["name" => "Zambia", "iso2" => "ZM", "iso3" => "ZMB", "phone_code" => "260", "currency_code" => "ZMW"],
            ["name" => "Zimbabwe", "iso2" => "ZW", "iso3" => "ZWE", "phone_code" => "263", "currency_code" => "ZWL"],
        ];

        foreach ($countries as &$c) {
            $c['is_active'] = true;
            $c['created_at'] = now();
            $c['updated_at'] = now();
        }

        DB::table('countries')->insert($countries);
    }
}
